// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OAM.Core.Entities;

public partial class User
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public byte[] PasswordHash { get; set; }

    public byte[] PasswordSalt { get; set; }

    public int RoleId { get; set; }

    public Guid? UserId { get; set; }

    public DateTime? CreatedTimeStamp { get; set; }

    public DateTime? UpdatedTimeStamp { get; set; }

    public bool? IsDeleted { get; set; }

    public decimal? PhoneNumber { get; set; }
}